server:
  port: 9011

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Lichuandi0911
# 多个配置环境时候切换
  profiles:
    active: dev
#配置jpa
 # jpa:
   # hibernate:
   #   ddl-auto: create #第一次建表使用crete，后面用update
  #  show-sql: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lichuandi.springcloud.entities

my:
  name: lichuandi
  age: 30
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,I am ${my.name}

#actuator监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      health:
        show-details: always
    shutdown:
        enabled: true
  server:
    port: 9001